name: xigua_ubuntu_rootfs

on:
  workflow_dispatch:

jobs:
  kernel:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 20
    strategy:
            matrix:
                version: [6.14]
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev python3 python-is-python3

      - name: Build kernel
        run: sudo sh xigua-kernel_build.sh ${{ github.workspace }} ${{ matrix.version }}

      - name: Upload linux.deb
        uses: actions/upload-artifact@v4
        with:
          name: linux-oneplus-sm8550_${{ matrix.version }}
          path: ${{ github.workspace }}/linux-oneplus-sm8550.deb

      - name: Upload 24G RAM boot.img
        uses: actions/upload-artifact@v4
        with:
          name: boot-oneplus-xigua_${{ matrix.version }}_24G_A15.img
          path: ${{ github.workspace }}/boot24G.img

  rootfs:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 20
    strategy:
            matrix:
                desktop: [ubuntu-desktop]
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt update && sudo apt install unzip bash tar git wget dpkg

      - name: Build rootfs
        run: sudo sh mainline-rootfs_build.sh ${{ matrix.desktop }} ${{ github.workspace }}

      - name: Upload rootfs.img
        uses: actions/upload-artifact@v4
        with:
          name: between_${{ matrix.desktop }}
          path: ubuntu-rootfs.7z
          compression-level: 0

  alsa:
    needs: rootfs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - name: Pack Alsa Use Case Configuration into .deb
        run: cd ${{ github.workspace }} && dpkg-deb --build --root-owner-group alsa-oneplus-sm8550

      - name: Upload alsa.deb
        uses: actions/upload-artifact@v4
        with:
          name: alsa-oneplus-sm8550
          path: ${{ github.workspace }}/alsa-oneplus-sm8550.deb

  firmware-a15:
    needs: rootfs
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt update && sudo apt install gcc make git wget dpkg

      - name: Squash firmwares to .mbn
        run: sudo sh xigua-fw_squasher-a15.sh ${{ github.workspace }}

      - name: Upload firmware.deb
        uses: actions/upload-artifact@v4
        with:
          name: firmware-oneplus-a15
          path: ${{ github.workspace }}/firmware-oneplus-a15.deb

  rootfs-packager:
    needs: [kernel, alsa, firmware-a15]
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    strategy:
            matrix:
                desktop: [ubuntu-desktop]
                kernel: [6.14]
                android: [15]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: between_${{ matrix.desktop }}*   
      - uses: actions/download-artifact@v4
        with:
          pattern: alsa-oneplus-sm8550*
      - uses: actions/download-artifact@v4
        with:
          pattern: firmware-oneplus-a${{ matrix.android }}*
      - uses: actions/download-artifact@v4
        with:
          pattern: linux-oneplus-sm8550_${{ matrix.kernel }}
      - name: Install Dependencies
        run: sudo apt update && sudo apt install unzip 7zip bash tar git wget dpkg

      - name: Package rootfs
        run: sudo sh mainline-rootfs_package.sh ${{ github.workspace }} ${{ matrix.android }}
        
      - name: Upload rootfs.7z
        uses: actions/upload-artifact@v4
        with:
          name: rootfs_${{ matrix.desktop }}_${{ matrix.kernel }}_A${{ matrix.android }}
          path: ubuntu-rootfs.7z
          compression-level: 0
          
  cleaner:
    runs-on: ubuntu-24.04-arm
    needs: rootfs-packager
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: between_*
